### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by nmeaux** [scibian/clara#2]
Hello,

On a fresh new system one package is missing for clara to get it work : 

```
# clara images create test
Traceback (most recent call last):
  File "/usr/bin/clara", line 69, in <module>
    from clara.utils import clara_exit, conf, initialize_logger
  File "/usr/lib/python2.7/dist-packages/clara/utils.py", line 43, in <module>
    import ClusterShell.NodeSet
ImportError: No module named ClusterShell.NodeSet
# apt-get install python-clustershell
```

rgds

Nicolas

**Comment by rezib** [comment]
Hi @nmeaux,

Thanks for the report!

Are you using Debian buster?

Actually, `clara-plugins-images` depends on `clara-core` which depends on `clustershell`. The later brings clustershell python2 library up to stretch, but depends on `python3-clustershell` on Debian buster. We do not support Clara nor provide packages on Debian buster scibian10 yet. If so, we will deliver the python3 version of clara, and no additional fix is required for clara.
